name: Test Deploy Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Verifier le serveur
        shell: pwsh
        run: |
          Write-Host "Serveur CI/CD :"
          hostname
          Write-Host "Utilisateur :"
          whoami

      - name: Deployer le script
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path "C:\Deploy" -Force
          Copy-Item ".\deploy-test.ps1" "C:\Deploy\deploy-test.ps1" -Force

          Write-Host "Fichier deploye :"
          Get-Item "C:\Deploy\deploy-test.ps1"

      - name: Tester le fichier deploye
        shell: powershell
        run: |
          & "C:\Deploy\deploy-test.ps1"
